name: Publish packages

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  packages: write
  contents: read
    
jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF/refs\/tags\//}"
          else
            SHORT_SHA=${GITHUB_SHA::7}
            VERSION="0.0.0-pr.${SHORT_SHA}"
          fi
          echo "PACKAGE_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash
      - uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '10.0.x' # SDK Version to use.
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          
      - name: Install MAUI workload
        run: dotnet workload install maui         
      - run: dotnet build --configuration Release ./src /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}
      - name: Create the package
        run: dotnet pack --configuration Release ./src -o . /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}
 #     - name: Publish the package to Nuget
 #       run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate
