name: Publish packages

on:
  pull_request:
  release:
    types: [created]

env:
  PathToScreensProject: ./src/OSK.Maui.Screens/OSK.Maui.Screens.csproj
  PathToScreensBlazorProject: ./src/OSK.Maui.Screens.Blazor/OSK.Maui.Screens.Blazor.csproj
  PathToScreensCommunityProject: ./src/OSK.Maui.Screens.CommunityToolkit/OSK.Maui.Screens.CommunityToolkit.csproj
  PathToScreensMopupsProject: ./src/OSK.Maui.Screens.Mopups/OSK.Maui.Screens.Mopups.csproj
  PathToBlazorPopupProject: ./src/OSK.Maui.Screens.Blazor.PopupPage/OSK.Maui.Screens.Blazor.PopupPage.csproj

permissions:
  packages: write
  contents: read
    
jobs:
  publish-nuget:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF/refs\/tags\//}"
          else
            SHORT_SHA=${GITHUB_SHA::7}
            VERSION="0.0.0-pr.${SHORT_SHA}"
          fi
          echo "PACKAGE_VERSION=$VERSION" >> "$GITHUB_OUTPUT"
        shell: bash
      - uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '10.x' # SDK Version to use.
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          
      - name: Install MAUI workload
        run: dotnet workload install maui       


# Builds
      - name: Build Screens Project
        run: dotnet build --configuration Release ${{ env.PathToScreensProject }} /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}

      - name: Build Blazor Project
        run: dotnet build ${{ env.PathToScreensBlazorProject }} -c Release /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}

      - name: Build Blazor PopupPage Project
        run: dotnet build ${{ env.PathToBlazorPopupProject }} -c Release /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }} /p:_ContentManifestDependsOn=" "

      - name: Build Screens Community Project
        run: dotnet build --configuration Release ${{ env.PathToScreensCommunityProject }} /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}

      - name: Build Screens Mopups Project
        run: dotnet build --configuration Release ${{ env.PathToScreensMopupsProject }} /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}

# Packages
      - name: Pack Screens Project
        run: dotnet pack --configuration Release ${{ env.PathToScreensProject }} -o . /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}

      - name: Pack Blazor Project
        run: dotnet pack --configuration Release ${{ env.PathToScreensBlazorProject }} -o . /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}

      - name: Pack Blazor PopupPage Project
        run: dotnet pack --configuration Release ${{ env.PathToBlazorPopupProject }} -o . /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }} /p:_ContentManifestDependsOn=" "

      - name: Pack Screens Community Project
        run: dotnet pack --configuration Release ${{ env.PathToScreensCommunityProject }} -o . /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}
      
      - name: Pack Screens Mopups Project
        run: dotnet pack --configuration Release ${{ env.PathToScreensMopupsProject }} -o . /p:Version=${{ steps.get_version.outputs.PACKAGE_VERSION }}
 
 # Publish
 #     - name: Publish the package to Nuget
 #       run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate
